log:
    level: error
api:
  dashboard: true
  debug: false
serversTransport:
  insecureSkipVerify: true
entryPoints:
  http:
    address: :80
  https:
    address: :443
providers:
  file:
    filename: /etc/traefik/config.yml
  docker:
    watch: true
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: test_task_traefik